"""Deterministic IDE adapters generated from the canonical MASE rules."""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Union


ADAPTERS = (
    "AGENTS.md",
    "CLAUDE.md",
    "CONVENTIONS.md",
    ".github/copilot-instructions.md",
)
HASH_PATTERN = re.compile(r"source_hash=([0-9a-f]{64})")
BODY_HASH_PATTERN = re.compile(r"body_hash=([0-9a-f]{64})")


@dataclass(frozen=True)
class RuleChange:
    path: Path
    action: str
    reason: str
    content: Optional[str] = None


class RuleSynchronizer:
    def __init__(self, source: Union[str, Path], *, source_text: Optional[str] = None):
        self.source = Path(source)
        self.source_text = (
            self.source.read_text(encoding="utf-8") if source_text is None else source_text
        )
        self.source_hash = hashlib.sha256(self.source_text.encode("utf-8")).hexdigest()

    def render(self, target: str) -> str:
        body = (
            "# MASE IDE adapter\n\n"
            "Before changing or reviewing this project, read `project-rules.md`. "
            "It is the only maintained rule source.\n\n"
            "MASE purpose: 让 Agentic Coding 高效交付正确、健壮、优化且易于维护的代码. "
            "Judge every trade-off by five outcomes: 高效交付、需求正确、运行健壮、"
            "质量优化、整洁可维护.\n\n"
            "Hard minimum: confirm user-visible behavior; test before implementation; "
            "analyze impact before historical behavior changes, protect baseline tests and "
            "reconcile actual paths, call edges and side effects; "
            "keep API contracts and P0 E2E green; diagnose root causes; back up before "
            "destructive migration. For releases, bind an immutable artifact identity, verify "
            "live consumer behavior, and retain tested recovery through observation. "
            "Keep product code, data, backups, demos, and generated caches outside the MASE "
            "framework repository. "
            "Load detailed docs and Skill references only when the "
            "current Profile, risk, or task routes to them.\n"
        )
        body_hash = hashlib.sha256(body.encode("utf-8")).hexdigest()
        header = (
            f"<!-- generated by MASE; source=project-rules.md; "
            f"source_hash={self.source_hash}; body_hash={body_hash}; target={target} -->\n"
        )
        return header + body

    def render_all(self) -> dict[str, str]:
        return {target: self.render(target) for target in ADAPTERS}

    @staticmethod
    def extract_source_hash(content: str) -> Optional[str]:
        match = HASH_PATTERN.search(content)
        return match.group(1) if match else None

    @staticmethod
    def _body_is_unmodified(content: str) -> bool:
        expected = BODY_HASH_PATTERN.search(content)
        if not expected:
            return False
        body = content.split("\n", 1)[1] if "\n" in content else ""
        actual = hashlib.sha256(body.encode("utf-8")).hexdigest()
        return actual == expected.group(1)

    def plan(self, project_dir: Union[str, Path]) -> list[RuleChange]:
        root = Path(project_dir)
        changes: list[RuleChange] = []
        for relative, desired in self.render_all().items():
            target = root / relative
            if not target.exists():
                changes.append(RuleChange(target, "create", "adapter missing", desired))
                continue
            current = target.read_text(encoding="utf-8")
            if current == desired:
                changes.append(RuleChange(target, "none", "already synchronized"))
            elif self.extract_source_hash(current) is not None and self._body_is_unmodified(current):
                changes.append(RuleChange(target, "update", "generated adapter source changed", desired))
            elif self.extract_source_hash(current) is not None:
                changes.append(RuleChange(target, "conflict", "generated adapter body was modified", desired))
            else:
                changes.append(RuleChange(target, "conflict", "unmanaged target already exists", desired))
        return changes

    def write_missing(self, project_dir: Union[str, Path]) -> list[RuleChange]:
        plan = self.plan(project_dir)
        for item in plan:
            if item.action in {"create", "update"} and item.content is not None:
                item.path.parent.mkdir(parents=True, exist_ok=True)
                item.path.write_text(item.content, encoding="utf-8")
        return plan
